import fs from 'fs';
import path from 'path';

export interface InstructionMessage {
  type: 'instruction';
  instruction: string;
  metadata?: {
    userId?: string;
    timestamp?: string;
    [key: string]: unknown;
  };
}

export interface InstructionResult {
  success: boolean;
  filename: string;
  message: string;
  error?: string;
}

export class InstructionHandler {
  private tasksDir: string;

  constructor(projectRoot: string) {
    this.tasksDir = path.join(projectRoot, 'tasks');
    this.ensureTasksDirectory();
  }

  /**
   * Ensure tasks directory exists
   */
  private ensureTasksDirectory(): void {
    if (!fs.existsSync(this.tasksDir)) {
      fs.mkdirSync(this.tasksDir, { recursive: true });
      console.log(`Created tasks directory: ${this.tasksDir}`);
    }
  }

  /**
   * Validate instruction message
   */
  public validateInstruction(message: unknown): message is InstructionMessage {
    if (typeof message !== 'object' || message === null) {
      return false;
    }

    const msg = message as Partial<InstructionMessage>;

    return (
      msg.type === 'instruction' &&
      typeof msg.instruction === 'string' &&
      msg.instruction.trim().length > 0
    );
  }

  /**
   * Handle instruction and create task file
   */
  public async handleInstruction(message: InstructionMessage): Promise<InstructionResult> {
    try {
      // Generate filename with timestamp
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `MANUS-REQUEST-${timestamp}.md`;
      const filePath = path.join(this.tasksDir, filename);

      // Generate task file content
      const content = this.generateTaskFileContent(message);

      // Write file
      await fs.promises.writeFile(filePath, content, 'utf-8');

      console.log(`Created task file: ${filename}`);

      return {
        success: true,
        filename,
        message: 'Task file created successfully',
      };
    } catch (error) {
      console.error('Error creating task file:', error);
      return {
        success: false,
        filename: '',
        message: 'Failed to create task file',
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  /**
   * Generate task file content from template
   */
  private generateTaskFileContent(message: InstructionMessage): string {
    const timestamp = new Date().toISOString();
    const userId = message.metadata?.userId || 'Unknown';

    return `# Manus Request - ${timestamp}

## Instruction from Mobile App

**User**: ${userId}
**Timestamp**: ${timestamp}

### Instruction

${message.instruction}

---

## Metadata

\`\`\`json
${JSON.stringify(message.metadata || {}, null, 2)}
\`\`\`

---

## Status

- [ ] Reviewed by Manus
- [ ] Assigned to Claude instance
- [ ] Task created
- [ ] Implementation complete

---

**Note**: This file was automatically generated by the Remote Cursor PC Agent Server.
`;
  }
}
